services:
  ffmpeg:
    image: ghcr.io/liofal/ffmpeg:1.0.0
    container_name: ffmpeg
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    
    env_file: 
        - .env
        # - ../global.env    
    volumes:
      - /Volumes/twitch:/app/downloads
