version: '3.7'

services:
  ffmpeg:
    image: liofal/ffmpeg
    container_name: ffmpeg
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: 
        - .env
        # - ../global.env    
    hostname: ffmpeg.liofal.net
    volumes:
      - /users/lionelfalise/Downloads:/work
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M

