name: Semantic Release

on:
  workflow_call:
    outputs:
      published:
        description: 'Whether a new version was published'
        value: ${{ jobs.release.outputs.published }}
      version:
        description: 'The new version'
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.semantic.outputs.new_release_published }}
      version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run semantic-release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
